spring:
  application:
    name: tracker
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

kotak:
  auth:
    token: ${KOTAK_TOKEN}

firebase:
  config:
    path: ${FIREBASE_CONFIG_PATH}


frontend:
  url: ${FRONTEND_URL}
