name: Deploy Tracker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USER }}/tracker:latest .

      - name: Push Image
        run: docker push ${{ secrets.DOCKER_USER }}/tracker:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            name: Deploy Tracker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USER }}/tracker:latest .

      - name: Push Image
        run: docker push ${{ secrets.DOCKER_USER }}/tracker:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu

            echo '${{ secrets.FIREBASE_JSON }}' > firebase.json

            docker pull ${{ secrets.DOCKER_USER }}/tracker:latest
            docker stop tracker || true
            docker rm tracker || true

            docker run -d -p 8080:8080 \
              --name tracker \
              -e DB_URL=${{ secrets.DB_URL }} \
              -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              -e KOTAK_TOKEN=${{ secrets.KOTAK_TOKEN }} \
              -e FIREBASE_CONFIG_PATH=/app/firebase.json \
              -e FRONTEND_URL=${{ secrets.FRONTEND_URL }} \
              -v /home/ubuntu/firebase.json:/app/firebase.json \
              ${{ secrets.DOCKER_USER }}/tracker:latest